# Generated by Django 5.2 on 2026-01-27 00:07

import curriculum.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_datospersonales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['-fecha_realizacion'], 'verbose_name_plural': 'Cursos y Formaciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Estudios Realizados (Educación)'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Experiencias Laborales'},
        ),
        migrations.AlterModelOptions(
            name='productolaboral',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Productos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['-fecha_obtencion'], 'verbose_name_plural': 'Reconocimientos y Premios'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Venta de Garage'},
        ),
        migrations.RemoveField(
            model_name='productolaboral',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en CV'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_realizacion',
            field=models.DateField(null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_seccion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiorealizado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en CV'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en CV'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en CV'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='fecha_publicacion',
            field=models.DateField(null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en CV'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='fecha_obtencion',
            field=models.DateField(null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cursos/certificados/'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[curriculum.models.validar_fecha_nacimiento]),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='educacion/certificados/'),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_fin',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_inicio',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='empresa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar en blanco si trabaja actualmente', null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='proyectos/archivos/'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='institucion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Nuevo', 'Nuevo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
