# Generated by Django 5.2 on 2026-01-27 00:36

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_cursocapacitacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Clasificación',
                'verbose_name_plural': 'Etiquetas de Clasificación',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField(validators=[curriculum.models.validar_no_futuro])),
                ('archivo', models.FileField(blank=True, null=True, upload_to='academicos/')),
                ('activo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, to='curriculum.categoriatag', verbose_name='Clasificación (Tags)')),
            ],
            options={
                'verbose_name': 'Producto Académico',
                'verbose_name_plural': '4. Producción Intelectual y Académica',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.DeleteModel(
            name='ProductoLaboral',
        ),
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['-fecha_realizacion'], 'verbose_name_plural': '5. Cursos y Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'verbose_name': '1. Información de Identidad', 'verbose_name_plural': '1. Información de Identidad'},
        ),
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['-fecha_fin'], 'verbose_name': 'Título Académico', 'verbose_name_plural': '3. Formación Académica (Educación)'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['-fecha_obtencion'], 'verbose_name_plural': '6. Reconocimientos y Premios'},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': '7. Venta de Garage'},
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='direccion_trabajo',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='licencia',
        ),
        migrations.RemoveField(
            model_name='datospersonales',
            name='url_instagram',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='codigo_registro',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='ventagarage',
            name='stock',
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='mostrar_seccion',
            field=models.BooleanField(default=True, verbose_name='Sección Activa'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='educacion/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Vacio si es Actual', null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=50),
        ),
    ]
