# Generated by Django 5.2 on 2026-01-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_categoriatag_productoacademico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
