# Generated by Django 5.2 on 2026-01-27 01:29

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_ventagarage_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='registro_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID / Registro de Propiedad'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Visible en la web'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='academicos/', verbose_name='Documentación (PDF/Zip)'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Detallada'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='fecha_publicacion',
            field=models.DateField(validators=[curriculum.models.validar_no_futuro], verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Producto'),
        ),
    ]
