# Generated by Django 5.2 on 2026-01-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_productoacademico_registro_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_inicio', models.BooleanField(default=True, verbose_name='Mostrar Inicio')),
                ('mostrar_perfil', models.BooleanField(default=True, verbose_name='Mostrar Perfil (Datos Personales)')),
                ('mostrar_experiencia', models.BooleanField(default=True, verbose_name='Mostrar Experiencia')),
                ('mostrar_educacion', models.BooleanField(default=True, verbose_name='Mostrar Educación')),
                ('mostrar_cursos', models.BooleanField(default=True, verbose_name='Mostrar Cursos')),
                ('mostrar_logros', models.BooleanField(default=True, verbose_name='Mostrar Logros/Reconocimientos')),
                ('mostrar_trabajos', models.BooleanField(default=True, verbose_name='Mostrar Trabajos')),
                ('mostrar_venta', models.BooleanField(default=True, verbose_name='Mostrar Sección Venta')),
                ('mostrar_contacto', models.BooleanField(default=True, verbose_name='Mostrar Contacto')),
            ],
            options={
                'verbose_name': 'Configuración de Visibilidad',
                'verbose_name_plural': 'Configuración de Visibilidad',
            },
        ),
    ]
