# Generated by Django 5.2 on 2026-01-27 03:18

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_configuracionpagina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['-fecha_fin'], 'verbose_name': 'Título Académico', 'verbose_name_plural': '3. Formación Académica'},
        ),
        migrations.AlterModelOptions(
            name='productoacademico',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Producto Académico', 'verbose_name_plural': '4. Producción Intelectual'},
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Vacío si es Actual', null=True, validators=[curriculum.models.validar_no_futuro]),
        ),
    ]
