# Generated by Django 5.2 on 2026-01-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_alter_estudiorealizado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': '2. Trayectoria Profesional'},
        ),
    ]
