# Generated by Django 5.2 on 2026-01-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_alter_experiencialaboral_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['fecha_obtencion'], 'verbose_name_plural': '6. Reconocimientos y Premios'},
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='codigo_registro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
