# Generated by Django 5.2 on 2026-01-29 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_alter_reconocimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='direccion_trabajo',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Trabajo'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='intereses',
            field=models.TextField(blank=True, help_text='Ej: Desarrollo web, diseño de interfaces, etc.', null=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='licencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Licencia'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='valores_profesionales',
            field=models.CharField(blank=True, help_text='Valores separados por comas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True, verbose_name='Bio (Resumen)'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugar_nacimiento',
            field=models.CharField(default='No especificado', max_length=100, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=20, verbose_name='Sexo / Género'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='url_linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría'), ('Nativo', 'Nativo')], max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='curriculum.datospersonales')),
            ],
        ),
    ]
