# Generated by Django 5.2 on 2026-01-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_datospersonales_direccion_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idioma',
            options={'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nivel',
            field=models.CharField(choices=[('A1', 'A1 - Principiante'), ('A2', 'A2 - Elemental'), ('B1', 'B1 - Intermedio'), ('B2', 'B2 - Intermedio Alto'), ('C1', 'C1 - Avanzado'), ('C2', 'C2 - Maestría'), ('Nativo', 'Nativo')], max_length=20, verbose_name='Nivel de Dominio'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(choices=[('Español', 'Español'), ('Inglés', 'Inglés'), ('Francés', 'Francés'), ('Alemán', 'Alemán'), ('Italiano', 'Italiano'), ('Portugués', 'Portugués'), ('Chino', 'Chino'), ('Japonés', 'Japonés'), ('Ruso', 'Ruso'), ('Otro', 'Otro')], max_length=50, verbose_name='Idioma'),
        ),
    ]
